feat: setup keycloak cluster

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -13,18 +13,20 @@ services:
     container_name: keycloak-1
     environment:
       KC_HOSTNAME: http://localhost:8084/auth #gateway  address on dev, use load balancer address on prod
+      KC_HOSTNAME_ADMIN: http://localhost:8084/auth
       KC_HTTP_ENABLED: true
 #      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
       KC_PROXY_HEADERS: xforwarded
       KC_HTTP_RELATIVE_PATH: /auth
-#      KC_HOSTNAME_ADMIN: http://localhost:8084/keycloak/admin #gateway  address on dev, use load balancer address on prod
       KC_LOG_LEVEL: DEBUG
       KC_BOOTSTRAP_ADMIN_USERNAME: admin
       KC_BOOTSTRAP_ADMIN_PASSWORD: admin
       KC_DB: postgres
       KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak_users
+#      KC_DB_URL: jdbc:postgresql://zeco-eats-db.c5mi08yoijvs.us-east-1.rds.amazonaws.com:5432/keycloak_users
       KC_DB_USERNAME: postgres
       KC_DB_PASSWORD: 1234
+     # KC_DB_PASSWORD: ppg9tJ6fDKQuJP91pkze
       KC_HEALTH_ENABLED: true
       KC_METRICS_ENABLED: true
       KC_CACHE: ispn
@@ -36,6 +38,14 @@ services:
       - keycloak-data:/opt/keycloak/data
     extra_hosts:
       - "host.docker.internal:host-gateway"
+    healthcheck:
+      test: [ "CMD-SHELL", "exec 3<> /dev/tcp/127.0.0.1/9000; 
+          echo -e 'GET /health/ready HTTP/1.1\\r\\nhost: http://localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3; 
+          if [ $? -eq 0 ]; then echo 'Healthcheck Successful'; exit 0; else echo 'Healthcheck Failed'; exit 1; fi;"
+      ]
+      interval: 10s
+      timeout: 5s
+      retries: 5
 
   keycloak-2:
     networks:
@@ -45,23 +55,40 @@ services:
     image: quay.io/keycloak/keycloak:26.1.3
     container_name: keycloak-2
     environment:
-#      KC_HOSTNAME: http://localhost:8084/auth #gateway  address on dev, use load balancer address on prod
-#      KC_HOSTNAME_ADMIN: http://localhost:8084/keycloak/admin #gateway  address on dev, use load balancer address on prod
+      KC_HOSTNAME: http://localhost:8084/auth #gateway  address on dev, use load balancer address on prod
+      KC_HOSTNAME_ADMIN: http://localhost:8084/auth
+      KC_HTTP_ENABLED: true
+      #      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
+      KC_PROXY_HEADERS: xforwarded
+      KC_HTTP_RELATIVE_PATH: /auth
+      KC_LOG_LEVEL: DEBUG
       KC_BOOTSTRAP_ADMIN_USERNAME: admin
       KC_BOOTSTRAP_ADMIN_PASSWORD: admin
+      KC_DB: postgres
+      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak_users
+      #KC_DB_URL: jdbc:postgresql://zeco-eats-db.c5mi08yoijvs.us-east-1.rds.amazonaws.com:5432/keycloak_users
       KC_DB_USERNAME: postgres
       KC_DB_PASSWORD: 1234
+      #KC_DB_PASSWORD: ppg9tJ6fDKQuJP91pkze
       KC_HEALTH_ENABLED: true
       KC_METRICS_ENABLED: true
       KC_CACHE: ispn
       KC_CACHE_STACK: jdbc-ping
     command:
-      start-dev
-      #start
+      #start-dev
+      start
     volumes:
       - keycloak-data:/opt/keycloak/data
     extra_hosts:
       - "host.docker.internal:host-gateway"
+    healthcheck:
+        test: [ "CMD-SHELL", "exec 3<> /dev/tcp/127.0.0.1/9000; 
+              echo -e 'GET /health/ready HTTP/1.1\\r\\nhost: http://localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3; 
+              if [ $? -eq 0 ]; then echo 'Healthcheck Successful'; exit 0; else echo 'Healthcheck Failed'; exit 1; fi;"
+        ]
+        interval: 10s
+        timeout: 5s
+        retries: 5
 
   ##KAFKA
   kafka-controller-1:
